/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture, useCubeTexture } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber'


export default function Model(props) {
  const { nodes, materials } = useGLTF("./models/MainScene/scene.gltf");

  const texture = useCubeTexture(
    ["px.png", "nx.png", "py.png", "ny.png", "pz.png" ,"nz.png"],
    {path: "./Standard-Cube-Map/"}
  ); 

  const [colorMap, displacementMap, normalMap, roughnessMap] = useLoader(TextureLoader, [
    './metal/Metal007_1K-JPG_Color.jpg',
    './metal/Metal007_1K-JPG_Displacement.jpg',
    './metal/Metal007_1K-JPG_NormalGL.jpg',
    './metal/Metal007_1K-JPG_Roughness.jpg',
  ])



  return (
    <group {...props} dispose={null} scale={5} position={[0,0,2.4]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FLOOR.geometry}
        material={nodes.FLOOR.material}
        position={[0, -0.001, 5.707]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK.geometry}
        material={nodes.BACK.material}
        position={[0, 3.316, -0.481]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pachinko1.geometry}
        material={materials.Mat}
        position={[0.288, -0.037, 0.446]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002_Plane.geometry}
        material={nodes.Plane002_Plane.material}
        position={[-5.581, 0.293, 0.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tube.geometry}
        material={nodes.tube.material}
        position={[0, 0, 5.177]}
      >
      <meshStandardMaterial
          normalMap={normalMap}
          roughnessMap={roughnessMap}
          color = {"#c78200"}
          envMap = {texture}
          envMapIntensity = {.1}
          metalness = {1}
          roughness= {1}
      />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/MainScene/scene.gltf");
